"""
RSI Threshold Optimizer

This script tests different RSI buy and sell threshold combinations on a selected BIST100 stock.
The user can enter either a BIST100 ticker symbol or a company name listed in data/bist100_companies.csv.

It runs a simple grid search backtest and exports the optimization heatmap as a timestamped image.

Strategy logic:
- Buy when RSI falls below the selected buy threshold.
- Sell when RSI rises above the selected sell threshold.
- At the end of the test period, any open position is closed at the latest available price.

Heatmap interpretation:
- Each cell represents the net profit generated by one RSI buy/sell threshold pair.
- The x-axis represents the sell RSI threshold.
- The y-axis represents the buy RSI threshold.
- The blue star marks the threshold pair that produced the highest final capital in the historical backtest.
- For example, if the best result is Buy RSI = 28 and Sell RSI = 66, the tested strategy would buy when RSI falls below 28 and sell when RSI rises above 66.

Financial interpretation:
- A low RSI value may indicate short-term oversold conditions.
- A high RSI value may indicate short-term overbought conditions.
- This optimizer does not generate a live buy/sell recommendation by itself.
- It only identifies which RSI threshold combination performed best on historical data for the selected stock.

Output:
- Terminal summary report
- Timestamped heatmap image in the outputs/ folder

Example output file:
- outputs/rsi_optimization_THYAO_2026-06-10_16-25-30.png

This project is for educational and research purposes only.
It does not provide financial advice.

"""

from datetime import datetime
from pathlib import Path
import unicodedata

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import yfinance as yf


PERIOD = "2y"
INITIAL_CAPITAL = 10_000

RSI_PERIOD = 14
BUY_RANGE = range(20, 50, 2)
SELL_RANGE = range(55, 90, 2)

OUTPUT_DIR = "outputs"
COMPANY_DATA_PATH = "data/bist100_companies.csv"


def normalize_text(text: str) -> str:
    """Normalize text for ticker, company name, and alias matching."""
    text = str(text).strip().lower()

    text = text.replace("ı", "i").replace("ğ", "g").replace("ü", "u")
    text = text.replace("ş", "s").replace("ö", "o").replace("ç", "c")

    text = unicodedata.normalize("NFKD", text)
    text = "".join(character for character in text if not unicodedata.combining(character))

    return " ".join(text.split())


def load_company_database(csv_path: str = COMPANY_DATA_PATH) -> pd.DataFrame:
    """Load BIST100 company name and ticker mapping from a CSV file."""
    company_data = pd.read_csv(csv_path)

    required_columns = {"ticker", "company_name", "aliases"}
    missing_columns = required_columns - set(company_data.columns)

    if missing_columns:
        raise ValueError(f"Missing columns in company database: {missing_columns}")

    return company_data


def resolve_symbol(user_input: str, company_data: pd.DataFrame) -> str:
    """
    Convert user input into a Yahoo Finance BIST100 symbol.

    Accepted examples:
    - THYAO
    - THYAO.IS
    - Türk Hava Yolları
    - Aselsan
    - Tüpraş
    """
    normalized_input = normalize_text(user_input)

    for _, row in company_data.iterrows():
        ticker = str(row["ticker"]).strip().upper()
        company_name = normalize_text(row["company_name"])

        aliases_raw = str(row["aliases"])
        aliases = aliases_raw.split(";")
        normalized_aliases = [normalize_text(alias) for alias in aliases]

        ticker_without_suffix = ticker.replace(".IS", "").lower()

        valid_inputs = {
            ticker.lower(),
            ticker_without_suffix,
            company_name,
            *normalized_aliases,
        }

        if normalized_input in valid_inputs:
            return ticker

    raise ValueError(
        f"'{user_input}' was not found in the BIST100 company database. "
        "Please enter a valid BIST100 ticker or company name."
    )


def get_symbol_from_user(company_data: pd.DataFrame) -> str:
    """Ask the user for a BIST100 ticker or company name."""
    user_input = input("Enter a BIST100 ticker or company name: ")

    if not user_input.strip():
        raise ValueError("Input cannot be empty.")

    return resolve_symbol(user_input, company_data)


def download_price_data(symbol: str, period: str = PERIOD) -> pd.DataFrame:
    """Download historical price data from Yahoo Finance."""
    data = yf.download(symbol, period=period, progress=False, threads=False)

    if isinstance(data.columns, pd.MultiIndex):
        data.columns = data.columns.get_level_values(0)

    return data.dropna()


def calculate_rsi(close_prices: pd.Series, period: int = RSI_PERIOD) -> pd.Series:
    """Calculate the Relative Strength Index using exponential moving averages."""
    delta = close_prices.diff()

    gain = delta.where(delta > 0, 0).ewm(com=period - 1, adjust=False).mean()
    loss = (-delta.where(delta < 0, 0)).ewm(com=period - 1, adjust=False).mean()

    relative_strength = gain / loss
    rsi = 100 - (100 / (1 + relative_strength))

    return rsi


def backtest_rsi_strategy(
    prices: np.ndarray,
    rsi_values: np.ndarray,
    buy_threshold: int,
    sell_threshold: int,
    initial_capital: float = INITIAL_CAPITAL,
) -> float:
    """Run a simple all-in/all-out RSI strategy backtest and return final capital."""
    cash = initial_capital
    shares = 0.0
    in_position = False

    for i in range(1, len(prices)):
        current_price = prices[i]
        current_rsi = rsi_values[i]

        if np.isnan(current_rsi):
            continue

        if current_rsi < buy_threshold and not in_position:
            shares = cash / current_price
            cash = 0.0
            in_position = True

        elif current_rsi > sell_threshold and in_position:
            cash = shares * current_price
            shares = 0.0
            in_position = False

    if in_position:
        cash = shares * prices[-1]

    return cash


def optimize_rsi_thresholds(data: pd.DataFrame) -> tuple[pd.DataFrame, dict]:
    """Test RSI buy/sell threshold combinations and return optimization results."""
    close_prices = data["Close"]
    data = data.copy()
    data["RSI"] = calculate_rsi(close_prices)

    prices = close_prices.to_numpy()
    rsi_values = data["RSI"].to_numpy()

    results = []
    best_result = {
        "buy_threshold": None,
        "sell_threshold": None,
        "final_capital": -np.inf,
        "net_profit": -np.inf,
        "return_percent": -np.inf,
    }

    for buy_threshold in BUY_RANGE:
        row_results = []

        for sell_threshold in SELL_RANGE:
            final_capital = backtest_rsi_strategy(
                prices=prices,
                rsi_values=rsi_values,
                buy_threshold=buy_threshold,
                sell_threshold=sell_threshold,
            )

            net_profit = final_capital - INITIAL_CAPITAL
            row_results.append(net_profit)

            if final_capital > best_result["final_capital"]:
                best_result = {
                    "buy_threshold": buy_threshold,
                    "sell_threshold": sell_threshold,
                    "final_capital": final_capital,
                    "net_profit": net_profit,
                    "return_percent": (net_profit / INITIAL_CAPITAL) * 100,
                }

        results.append(row_results)

    result_table = pd.DataFrame(results, index=BUY_RANGE, columns=SELL_RANGE)

    return result_table, best_result


def create_timestamped_output_path(symbol: str, output_dir: str = OUTPUT_DIR) -> Path:
    """Create a unique timestamped heatmap output path."""
    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    clean_symbol = symbol.replace(".IS", "")
    output_folder = Path(output_dir)
    output_folder.mkdir(parents=True, exist_ok=True)

    return output_folder / f"rsi_optimization_{clean_symbol}_{timestamp}.png"


def save_heatmap(result_table: pd.DataFrame, best_result: dict, symbol: str) -> Path:
    """Save the RSI optimization heatmap as an image file."""
    output_path = create_timestamped_output_path(symbol)

    plt.figure(figsize=(12, 8))
    sns.heatmap(
        result_table,
        cmap="RdYlGn",
        center=0,
        annot=False,
        cbar_kws={"label": "Net Profit"},
    )

    best_buy = best_result["buy_threshold"]
    best_sell = best_result["sell_threshold"]

    plt.scatter(
        x=list(SELL_RANGE).index(best_sell) + 0.5,
        y=list(BUY_RANGE).index(best_buy) + 0.5,
        color="blue",
        s=200,
        marker="*",
        label="Best Result",
    )

    plt.title(f"{symbol} RSI Threshold Optimization")
    plt.xlabel("Sell RSI Threshold")
    plt.ylabel("Buy RSI Threshold")
    plt.legend()
    plt.tight_layout()
    plt.savefig(output_path, dpi=300)
    plt.close()

    return output_path


def print_summary(symbol: str, best_result: dict, heatmap_path: Path) -> None:
    """Print a clean terminal summary."""
    print("\nRSI Threshold Optimizer")
    print("=" * 70)
    print(f"Symbol           : {symbol}")
    print(f"Initial Capital  : {INITIAL_CAPITAL:,.2f}")
    print(f"Best Buy RSI     : {best_result['buy_threshold']}")
    print(f"Best Sell RSI    : {best_result['sell_threshold']}")
    print(f"Final Capital    : {best_result['final_capital']:,.2f}")
    print(f"Net Profit       : {best_result['net_profit']:,.2f}")
    print(f"Return           : {best_result['return_percent']:.2f}%")
    print(f"Heatmap saved to : {heatmap_path}")
    print("=" * 70)


if __name__ == "__main__":
    try:
        bist100_companies = load_company_database()
        selected_symbol = get_symbol_from_user(bist100_companies)

        print(f"\nDownloading data for {selected_symbol}...")

        price_data = download_price_data(selected_symbol)

        if price_data.empty:
            print(f"No price data found for {selected_symbol}. Please check the ticker or company name.")
        else:
            optimization_table, best_strategy_result = optimize_rsi_thresholds(price_data)
            saved_heatmap_path = save_heatmap(
                optimization_table,
                best_strategy_result,
                selected_symbol,
            )
            print_summary(selected_symbol, best_strategy_result, saved_heatmap_path)

    except FileNotFoundError:
        print(f"Company database not found: {COMPANY_DATA_PATH}")
    except ValueError as error:
        print(f"Input error: {error}")